workflows:
  android-release:
    name: Android Release Build
    environment:
      groups:
        - google_play # Erstelle eine Gruppe mit deinen Google Play Anmeldedaten in Codemagic
      android_signing:
        keystore: "keystore.jks" # Pfad zu deinem Keystore
        keystore_password: $CM_KEYSTORE_PASSWORD # Umgebungsvariable für Keystore-Passwort
        key_alias: "your_key_alias" # Dein Key-Alias
        key_password: $CM_KEY_PASSWORD # Umgebungsvariable für Key-Passwort
    scripts:
      - name: Set up keystore
        script: |
          echo $CM_KEYSTORE_BASE64 | base64 --decode > android/app/keystore.jks
      - name: Set up keystore properties
        script: |
          echo "storePassword=$CM_KEYSTORE_PASSWORD" > android/keystore.properties
          echo "keyPassword=$CM_KEY_PASSWORD" >> android/keystore.properties
          echo "keyAlias=your_key_alias" >> android/keystore.properties
      - name: Flutter build
        script: |
          flutter build appbundle --release
    artifacts:
      - build/app/outputs/bundle/release/app-release.aab
    publishing:
      google_play:
        credentials: $GOOGLE_PLAY_JSON_KEY_FILE # Umgebungsvariable für Google Play JSON-Key-File
        package_name: com.example.myapplication # Dein Package-Name
        track: alpha # Oder beta, production
        promote_to: production
