workflows:
  android-release:
    name: Android Release Build
    max_build_duration: 120
    environment:
      flutter: stable
      android_signing:
        - release_keystore  # Hier als Liste

    scripts:
      - flutter clean
      - flutter pub get
      - flutter build apk --release

    artifacts:
      - build/*/outputs//.apk

    publishing:
      google_play:
        credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
        track: internal  # Alternativ: 'production', 'beta', 'alpha'
        in_app_update_priority: 2  # Optional, kann entfernt werden
